# Generated by Django 5.1.6 on 2025-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_androidapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_logos/'),
        ),
        migrations.AlterField(
            model_name='androidapp',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
