# Generated by Django 5.1.6 on 2025-02-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_points_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
