# Generated by Django 5.1.6 on 2025-02-12 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.androidapp'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='image',
            field=models.ImageField(upload_to='task_images/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
