# Generated by Django 5.1.6 on 2025-02-12 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tasksubmission_status_alter_tasksubmission_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='status',
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.androidapp'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='image',
            field=models.ImageField(upload_to='task_submissions/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
