# Generated by Django 5.1.6 on 2025-02-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_joke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joke',
        ),
    ]
